on:
  push:
    branches: [main]

name: Test-Coverage

jobs:
  Test-Coverage:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GH_PAT }}

    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: sudo apt-get install -y libcurl4-openssl-dev
        shell: bash {0}

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R Dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::covr
          needs: coverage
          cache: always

      - name: Test coverage
        run: covr::codecov()
        shell: Rscript {0}

      - name: Upload Coverage
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: r-data-science/rdstools
